version: '3'
services:
  web:
    build:
        context: .
        dockerfile: Dockerfile

    command: npm start
    volumes:
      - .:/sharedServer/
      - /sharedServer/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
            DATABASE_URL: postgres://admin:admin@postgres:5432/sharedserverdb
            #DATABASE_URL: postgres://djqwxgjfyscimj:83a5f573529a2ccb5b12c90264ec524d233efa688690914bbd2c0f2252da1efd@ec2-54-221-210-97.compute-1.amazonaws.com:5432/debba01ukdah3q
            SECRET: secret

  postgres:
          image: postgres:latest 
          restart: always
          environment:
                POSTGRES_USER: admin
                POSTGRES_PASSWORD: admin
                POSTGRES_DB: sharedserverdb
          ports:
               - "5435:5432"
